### ISSUE TITLE
Plot function

### ISSUE THREAD

**Issue by alexanderlange53** [alexanderlange53/svars#16]
Generic plot function for impulse response functions with r-base as well as with ggplot

**Comment by BDalheimer** [comment]
Oddly, plot.svarIdent is exported as a function and not S3method but may be used as one (plot(...)). I updated the documentation accordingly

**Comment by BDalheimer** [comment]
The plot function is still exported as a function, not an S3method but works as one though. Maybe there's a problem with ggplot?
