### ISSUE TITLE
chow.test fails for "vec2var" class

### ISSUE THREAD

**Issue by runnytone** [alexanderlange53/svars#58]
chow.test fails for "vec2var" class.
There is something wrong with function get_var_objects.

**Comment by alexanderlange53** [comment]
Thank you for the comment. We are working on a solution and going to update the function asap.

**Comment by BDalheimer** [comment]
Thanks for pointing this out. There was indeed a problem in get_var_objects where the vec2var objects had been assigned in the upper level environment but not in the current one. Furthermore, the chow.test function was overwriting these assignments. The function should support vec2var objects now.
