### ISSUE TITLE
The cf function is not found

### ISSUE THREAD

**Issue by AmeerDZ1981** [alexanderlange53/svars#78]
I'm having a problem with the counterfactual analysis. The  `cf` function is not found

> counterfactuals <- cf(structural.form, series = 1)
> Error in cf(structural.form, series = 1) : could not find function "cf"

**Comment by BDalheimer** [comment]
Many thanks for raising this issue. The cf function will be part of the next package release on cran (coming soon). However, it is already part of the development version which you can install with ```devtools::install_github("alexanderlange53/svars")```

**Comment by AmeerDZ1981** [comment]
Many thanks for your reply, and I appreciate your effort to build this unique package. However, I have some suggestions regarding the plot of the impulse response function, I think it would be better if include the option of choosing the impulse and the response variables, rather than plotting them all together at once. Many packages of VAR models have this option such as `BVAR` package....etc

Best wishes

**Comment by BDalheimer** [comment]
Many thanks for this suggestion, this sounds indeed useful. We'll think about whether and how we can implement this in the next package version. In the meantime, I will close this issue since this is is becoming a different topic now.
